# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'PhotoGallery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'Alamofire'
  pod 'SDWebImageSwiftUI'
  # Pods for PhotoGallery

end
